### ISSUE TITLE
`get_link()` is not working on openfaas calls

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-servless-functions#27]
Report from Saulo:

The following code is returning an error:

```
from hyperon_das import DistributedAtomSpace
from hyperon_das.utils import QueryOutputFormat

host = '104.238.183.115'
port = '8081'
das = DistributedAtomSpace()
das.attach_remote(host=host, port=port)
print(f"Connected to DAS at {host}:{port}")
#print("(nodes, links) =", server.count_atoms())

result = das.remote_das[0].get_link(
    link_type='Inheritance',
    targets=['FBgg0001581', 'FBgg0001782'],
    output_format=QueryOutputFormat.HANDLE
)
print(f'Link:\n{result}')
```

```
Connected to DAS at 104.238.183.115:8081
Link:
{'error': '(\'This link does not exist\', "Inheritance:[\'FBgg0001581\', \'FBgg0001782\']")'}
```

However, the link do exist. The following query (which gets the same link) is answering correctly:

```
answer = self.server.query({
        "atom_type": "link",
        "type": "Inheritance",
        "targets": [
            {"atom_type": "node", "type": "Verbatim", "name": group_id},
            {"atom_type": "variable", "name": "v1"}
        ]
    })
```

```
Connected to DAS at 104.238.183.115:8081
[{'handle': '63a7285a1769cb945e4f2b08b551b627', 'type': 'Inheritance', 'template': ['Inheritance', 'Verbatim', 'Verbatim'], 'targets': [{'handle': '75c0cb62813232225d103fde73ed2309', 'type': 'Verbatim', 'name': 'FBgg0001581'}, {'handle': '2be7e8fefe304d09025502f169427254', 'type': 'Verbatim', 'name': 'FBgg0001782'}]}]

{"atom_type": "node", "type": "Verbatim", "name": group_id}
```

**Comment by andre-senna** [comment]
The code above is wrong.  But it still seems like we have a bug. Follows a fixed version of the code:

```
from typing import Any, Dict, List, Optional, Set, Tuple, Union 
from hyperon_das import DistributedAtomSpace 
 
host = '104.238.183.115' 
port = '8081' 
query_params = { 
    "toplevel_only": False, 
} 
 
das = DistributedAtomSpace(query_engine='remote', host=host, port=port) 
print(f"Connected to DAS at {host}:{port}") 
 
handle1 = das.get_node_handle('Verbatim', 'FBgg0001581') 
handle2 = das.get_node_handle('Verbatim', 'FBgg0001782') 
 
print(handle1, handle2) 
 
result = das.get_link( 
    link_type='Inheritance', 
    link_targets=[handle1, handle2] 
) 
print(f'Link:\n{result}')
```

This is raising this error:

```
[ninjato] ~/work/projects/das/pypi > python3 saulo_test_2.py 
Connected to DAS at 104.238.183.115:8081
75c0cb62813232225d103fde73ed2309 2be7e8fefe304d09025502f169427254
Traceback (most recent call last):
  File "/home/senna/work/projects/das/pypi/saulo_test_2.py", line 18, in <module>
    result = das.get_link(
  File "/home/senna/work/projects/das/github/das-query-engine/hyperon_das/das.py", line 143, in get_link
    return self.query_engine.get_link(link_type, link_targets)
  File "/home/senna/work/projects/das/github/das-query-engine/hyperon_das/das.py", line 587, in get_link
    local = self.local_query_engine.get_link(link_type, link_targets)
  File "/home/senna/work/projects/das/github/das-query-engine/hyperon_das/das.py", line 497, in get_link
    return self.local_backend.get_atom(link_handle)
  File "/home/senna/work/projects/das/github/das-atom-db/hyperon_das_atomdb/adapters/ram_only.py", line 320, in get_atom
    atom = self._replace_keys(document, atom_type)
  File "/home/senna/work/projects/das/github/das-atom-db/hyperon_das_atomdb/database.py", line 37, in _replace_keys
    answer = document.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by andre-senna** [comment]
Fixed in:

```
hyperon-das-atomdb 0.2.12
hyperon-das 0.3.14
```
